# Generated by Django 5.0.3 on 2024-04-08 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=500)),
                ('phone', models.CharField(help_text='10 digit Mobile Number', max_length=40)),
                ('emergency_contact', models.CharField(max_length=40)),
                ('profession', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('profile_pic', models.ImageField(default='patients_profile_pictures/defaultprofilepic.jpg', upload_to='patients_profile_pictures')),
                ('Aadhar_Number', models.IntegerField(help_text='12 digit unique Aadhar Number')),
                ('usertype', models.IntegerField(default=1)),
                ('access_code', models.IntegerField(default=1)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
