# Generated by Django 5.0.3 on 2024-04-08 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientRecordApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('doctor_name', models.CharField(max_length=100)),
                ('diagnosis', models.CharField(max_length=500)),
                ('Symptoms', models.CharField(max_length=500)),
                ('medication', models.CharField(max_length=500)),
                ('additional_precautions', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LabReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=100)),
                ('report_date', models.DateField()),
                ('upload_date', models.DateField(auto_now=True)),
                ('labreportfile', models.FileField(upload_to='lab_reports')),
                ('patientl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Height_in_Centimeters', models.CharField(help_text='Height in centimeters', max_length=100)),
                ('Weight_in_kilograms', models.CharField(help_text='Weight in kilograms', max_length=100)),
                ('Allergies', models.TextField(max_length=30)),
                ('Smoker_or_not', models.CharField(max_length=30)),
                ('Chronic_conditions', models.CharField(help_text='Your current long term diseases. <br>Ex. High BP, Diabetes etc', max_length=30)),
                ('patientv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
